name: arch_wizard
description: A simple command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0-333.2.beta

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  get_it: ^8.2.0
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  arch_wizard: # This makes the command `arch_wizard` directly available