name: arch_wizard
version: 1.0.4
description: A powerful CLI tool to scaffold Flutter clean architecture features...
repository: https://github.com/Meharab-Islam/arch_wizard.git

environment:
  sdk: '>=3.0.0 <4.0.0'

# Add regular dependencies here.
dependencies:
  args: ^2.4.2
  equatable: ^2.0.7
  get_it: ^8.2.0
  mason_logger: ^0.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0

executables:
  arch_wizard: # This makes the command `arch_wizard` directly available